title: Shrenik
author: Shrenik Patel
email: sdpatel@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is a website about me, Shrenik Patel. I am a passionate and hard-working person who values kindness as the fundamental base for success in life.

# social links
twitter_username: shrenikpatel_ # DO NOT include the @ character, or else the build will fail!
github_username:  sdpatel17 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
